version: '3.8'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./html:/var/www/html:ro
    restart: always
    networks:
      - external-network
networks:
  external-network: